# Generated by Django 5.0.4 on 2024-08-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Is active✅ / Is not active ❌', verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date when was created this record', verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='The date of last modification', verbose_name='Modified date')),
                ('deleted_date', models.DateTimeField(blank=True, help_text='The last date when the record was deleted or deactivated', null=True, verbose_name='Deleted date')),
                ('changed_by', models.BigIntegerField(help_text='The last user that touched this record', verbose_name='Changed by')),
                ('name', models.CharField(db_index=True, help_text='Nombre de la categoría', max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Is active✅ / Is not active ❌', verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date when was created this record', verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='The date of last modification', verbose_name='Modified date')),
                ('deleted_date', models.DateTimeField(blank=True, help_text='The last date when the record was deleted or deactivated', null=True, verbose_name='Deleted date')),
                ('changed_by', models.BigIntegerField(help_text='The last user that touched this record', verbose_name='Changed by')),
                ('name', models.CharField(help_text='Nombre del proveedor', max_length=150, verbose_name='Nombre')),
                ('nature', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJETO'), ('J', 'JURIDICO')], db_index=True, help_text='Naturaleza del proveedor, ya sea Juridico, Natural, Extranjero.', max_length=1, verbose_name='Naturaleza')),
                ('identification', models.CharField(db_index=True, help_text='RIF / Cedula de identidad', max_length=15, unique=True, verbose_name='Identificación')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Is active✅ / Is not active ❌', verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date when was created this record', verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='The date of last modification', verbose_name='Modified date')),
                ('deleted_date', models.DateTimeField(blank=True, help_text='The last date when the record was deleted or deactivated', null=True, verbose_name='Deleted date')),
                ('changed_by', models.BigIntegerField(help_text='The last user that touched this record', verbose_name='Changed by')),
                ('name', models.CharField(db_index=True, help_text='Nombre del producto', max_length=120, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción del producto', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta del producto en USD', max_digits=20, verbose_name='Precio (USD)')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Costo de adquisición del producto en USD', max_digits=20, verbose_name='Costo (USD)')),
                ('quantity', models.IntegerField(default=0, help_text='Cantidad disponible o almacenada del producto en el inventario', verbose_name='Cantidad')),
                ('categories', models.ManyToManyField(to='productos.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.supplier')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
