# Generated by Django 5.0.4 on 2024-08-17 17:46

from django.conf import settings
from django.db import migrations, models
from django.apps.registry import Apps # El tipado del apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

def foward_func(apps:Apps, schema_editor:BaseDatabaseSchemaEditor):
	# Función que se ejecuta al aplicar la migración
    User = apps.get_model("users", "User")
    User.objects.create_superuser(username="admin", password="admin", is_staff=True)


def reverse_func(apps:Apps, schema_editor:BaseDatabaseSchemaEditor):
	# Función que se ejecuta al revertir la migración
    User = apps.get_model("users", "User")
    User.objects.filter(username="admin").delete()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(foward_func, reverse_func),
    ]
